import {
  CompetitorChange,
  Recommendation,
  CustomerOpportunity,
  CompetitorSummary,
  MetricSummary,
} from '@/types'

export const mockMetricSummary: MetricSummary = {
  competitorsMonitored: 4,
  competitorsDelta: 0,
  changesDetected: 19,
  changesDelta: 12,
  negativeFeedbackRate: 28.4,
  negativeFeedbackDelta: 4.2,
  openRecommendations: 6,
  opportunitiesDetected: 14,
  qualifiedLeads: 5,
  conversionRate: 18.2,
  monitoringStatus: 'healthy',
}

export const mockCompetitors: CompetitorSummary[] = [
  {
    id: 'comp_mixpanel',
    name: 'Mixpanel',
    websiteUrl: 'https://mixpanel.com',
    status: 'active',
    lastCheckedTime: '18 minutes ago',
    monitoringFrequency: 'Every 12h',
    pricingSummary: 'Starts $35/mo (per-event usage tiers)',
    featureSummary: 'Product analytics, cohort funnels, retention tables',
    riskLevel: 'critical',
    sourcesCount: 4,
  },
  {
    id: 'comp_amplitude',
    name: 'Amplitude',
    websiteUrl: 'https://amplitude.com',
    status: 'active',
    lastCheckedTime: '42 minutes ago',
    monitoringFrequency: 'Every 12h',
    pricingSummary: 'Custom quote above 50k MTU',
    featureSummary: 'Digital analytics, experimentation, session replay',
    riskLevel: 'high',
    sourcesCount: 3,
  },
  {
    id: 'comp_posthog',
    name: 'PostHog',
    websiteUrl: 'https://posthog.com',
    status: 'active',
    lastCheckedTime: '1 hour ago',
    monitoringFrequency: 'Every 24h',
    pricingSummary: 'Pay-per-event after 1M free events',
    featureSummary: 'Analytics, recordings, feature flags, surveys',
    riskLevel: 'medium',
    sourcesCount: 4,
  },
  {
    id: 'comp_heap',
    name: 'Heap (Contentsquare)',
    websiteUrl: 'https://heap.io',
    status: 'active',
    lastCheckedTime: '3 hours ago',
    monitoringFrequency: 'Every 24h',
    pricingSummary: 'Annual contract required for mid-market',
    featureSummary: 'Autocapture data science & retroactive analysis',
    riskLevel: 'low',
    sourcesCount: 2,
  },
]

export const mockCompetitorChanges: CompetitorChange[] = [
  {
    id: 'chg_101',
    competitorId: 'comp_mixpanel',
    competitorName: 'Mixpanel',
    changeType: 'pricing_change',
    previousValue: '$25/mo Starter Plan (100k events)',
    newValue: '$35/mo Starter Plan (capped at 90 days retention)',
    detectedDate: 'Today at 09:14 AM',
    importance: 'critical',
    impact: 'Price increased by 40% while retention query window decreased from 12 months to 90 days.',
    status: 'pending_review',
    sourceUrl: 'https://mixpanel.com/pricing',
    sourceType: 'Public Pricing Page',
  },
  {
    id: 'chg_102',
    competitorId: 'comp_posthog',
    competitorName: 'PostHog',
    changeType: 'new_feature',
    previousValue: 'Manual session inspection only',
    newValue: 'Automated Session Summary heuristic in public changelog',
    detectedDate: 'Yesterday at 04:30 PM',
    importance: 'medium',
    impact: 'Shipped automated session diagnostic flags to reduce playback review time.',
    status: 'reviewed',
    sourceUrl: 'https://posthog.com/changelog',
    sourceType: 'Public Changelog Feed',
  },
  {
    id: 'chg_103',
    competitorId: 'comp_amplitude',
    competitorName: 'Amplitude',
    changeType: 'positioning_change',
    previousValue: '"#1 Product Analytics Platform for Growth"',
    newValue: '"The Complete Digital Analytics and Experimentation Operating System"',
    detectedDate: 'Sep 05, 2026',
    importance: 'high',
    impact: 'Pivoted hero headline copy from standalone analytics to unified experimentation platform.',
    status: 'action_taken',
    sourceUrl: 'https://amplitude.com',
    sourceType: 'Homepage DOM Snapshot',
  },
  {
    id: 'chg_104',
    competitorId: 'comp_heap',
    competitorName: 'Heap',
    changeType: 'removed_feature',
    previousValue: 'Self-serve monthly plan option',
    newValue: 'Replaced with "Contact Sales" enterprise gate',
    detectedDate: 'Sep 03, 2026',
    importance: 'high',
    impact: 'Removed self-serve card checkout; all new users must go through a sales demo.',
    status: 'reviewed',
    sourceUrl: 'https://heap.io/pricing',
    sourceType: 'Public Pricing Page',
  },
  {
    id: 'chg_105',
    competitorId: 'comp_mixpanel',
    competitorName: 'Mixpanel',
    changeType: 'support_complaint_trend',
    previousValue: '6.2% pricing complaint ratio in public threads',
    newValue: '21.8% pricing complaint ratio (spike following bill surge)',
    detectedDate: 'Sep 02, 2026',
    importance: 'critical',
    impact: 'Statistical text classification detected 3.5x increase in "unexpected bill" and "overage" terms.',
    status: 'pending_review',
    sourceUrl: 'https://reddit.com/r/SaaS',
    sourceType: 'Public Discussion Monitor',
  },
]

export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec_01',
    title: 'Publish "No Surprise Invoices" Callout on Pricing Table',
    problem: '42% of competitor complaints in the past 30 days cite unpredictable overage invoices as the primary reason for seeking alternatives.',
    evidence: 'Mixpanel increased Starter pricing by 40% and forum complaints containing overage terms surged to 21.8%.',
    sourceUrl: 'https://mixpanel.com/pricing',
    reason: 'Rule-engine pattern match: Competitor pricing increase + complaint surge = High-conversion messaging opportunity.',
    priority: 'critical',
    confidenceScore: 0.94,
    expectedImpact: 'Estimated 15-20% increase in visitor-to-trial conversion from self-serve SaaS switchers.',
    suggestedAction: 'Add a prominent badge above plan comparison: "Predictable flat monthly pricing. No surge penalties when your app goes viral."',
    status: 'pending',
    createdDate: 'Sep 06, 2026',
  },
  {
    id: 'rec_02',
    title: 'Highlight 1-Line SDK vs. Heavy Script Overhead',
    problem: 'Prospects evaluating competitors frequently complain about client-side script performance impact.',
    evidence: 'PostHog bundle footprint measured at 48KB gzipped vs. your lightweight 5.8KB script.',
    sourceUrl: 'https://posthog.com/docs',
    reason: 'Deterministic benchmark gap: Your script is 8.2x smaller than the competitor average.',
    priority: 'high',
    confidenceScore: 0.89,
    expectedImpact: 'Strong technical differentiator for engineering-led SaaS buyers concerned with Core Web Vitals.',
    suggestedAction: 'Create a dedicated "Performance & Bundle Size" benchmark comparison card in the documentation.',
    status: 'in_progress',
    createdDate: 'Sep 04, 2026',
  },
  {
    id: 'rec_03',
    title: 'Add Segment / RudderStack One-Click Destination Integration',
    problem: 'Switching friction: prospective customers cite pipeline re-instrumentation as the #1 blocker to migrating.',
    evidence: '5 out of 8 high-intent prospect comments mention existing Segment pipelines.',
    sourceUrl: 'https://news.ycombinator.com',
    reason: 'Taxonomy matching: Customer data platform ingestion removes 80% of migration work.',
    priority: 'high',
    confidenceScore: 0.92,
    expectedImpact: 'Reduces trial-to-active onboarding drop-off from 38% to under 15%.',
    suggestedAction: 'Prioritize native Segment destination protocol in current sprint.',
    status: 'accepted',
    createdDate: 'Sep 01, 2026',
  },
]

export const mockCustomerOpportunities: CustomerOpportunity[] = [
  {
    id: 'opp_201',
    opportunityScore: 0.94,
    sourcePlatform: 'Reddit (r/SaaS)',
    competitorName: 'Mixpanel',
    publicComment: '"Mixpanel just hit us with a $1,800 overage bill because our product had an unexpected spike on ProductHunt. Looking for an analytics tool with predictable flat monthly billing."',
    detectedProblem: 'Surprise variable overage billing during traffic surges',
    matchingProductFeature: 'Flat-rate $99/mo Growth tier with zero overage penalties',
    intentType: 'seeking_alternative',
    relevance: 'high',
    status: 'awaiting_approval',
    dateDetected: 'Today at 08:30 AM',
    sourceUrl: 'https://reddit.com/r/SaaS/comments/analytics_overage',
    draftMessage: 'Saw your post about the sudden overage invoice. We built our product specifically around flat-rate predictability ($99/mo with unlimited team members and no surge penalties). Happy to extend a 30-day sandbox trial if you want to inspect how funnels run without billing surprises.',
  },
  {
    id: 'opp_202',
    opportunityScore: 0.88,
    sourcePlatform: 'Hacker News',
    competitorName: 'Amplitude',
    publicComment: '"We spent 3 weeks trying to instrument Amplitude and our non-technical marketers still cannot create a retention cohort without writing custom JQL queries. It is way too complex for an early stage team."',
    detectedProblem: 'Excessive setup complexity & poor marketer usability',
    matchingProductFeature: 'No-code visual funnel builder & 5-minute setup script',
    intentType: 'seeking_alternative',
    relevance: 'high',
    status: 'draft_created',
    dateDetected: 'Yesterday',
    sourceUrl: 'https://news.ycombinator.com/item?id=3891024',
    draftMessage: 'Hi there — noticed your note on Amplitude setup overhead. Our visual cohort builder was engineered for marketing and growth teams to build conversion funnels in under 5 minutes without writing custom queries.',
  },
  {
    id: 'opp_203',
    opportunityScore: 0.82,
    sourcePlatform: 'Twitter / X',
    competitorName: 'Heap',
    publicComment: '"Heap removed their self-serve plans. Forced into an annual contract call for a simple web app. Any good modern alternatives that let you just swipe a card?"',
    detectedProblem: 'Forced enterprise sales gating for self-serve buyers',
    matchingProductFeature: 'Transparent credit card checkout with month-to-month flexibility',
    intentType: 'seeking_alternative',
    relevance: 'medium',
    status: 'needs_review',
    dateDetected: '2 days ago',
    sourceUrl: 'https://x.com/tech_founder_demo',
  },
]
